id: P000114
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །དྭགས་པོ་ཆོས་བཞིའི་རྩ་བ་སྐྱེས་བུ་གསུམ་གྱི་ལམ་གྱི་མཆོག་རིན་པོ་ཆེའི་འཕྲེང་བ་ཞེས་བྱ་བ་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། ཀུན་མཁྱེན་པདྨ་དཀར་པོ།
  layers:
  - book_title
  - author
  - chapter_title
  - tsawa
  - quotation
  - sabche
  id: KS-PK-08
web_metadata:
  title:
    en: Illuminating the Path for Three Scopes of Person:A Presentation of the Four
      Dharmas of Gampopa
    bo: དྭགས་པོའི་ཆོས་བཞིའི་རྣམ་བཤད་སྐྱེས་བུ་གསུམ་གྱི་ལམ་ཉིན་མོར་བྱེད་པ་ཞེས་བྱ་བ་བཞུགས་སོ།
      །
  collection:
    en: Pema Karpo Series–  Book 8
    bo: ཀུན་མཁྱེན་གཞུང་འགྲེལ།–  དེབ། ༨
  author:
    en: Kunkhyen Pema Karpo
    bo: ཀུན་མཁྱེན་པདྨ་དཀར་པོ།
  pusblisher:
    en: Gautam Buddha Vihara
    bo: དོན་བརྒྱུད་དཔལ་ལྡན་འབྲུག་པ།
  sku: KS-PK-08
  category:
    en: Stages of the Path
    bo: ལམ་རིམ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: KS-PK-08.epub
  description:
    en: ''
    bo: ''
